---
- name: Templating of the config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/bind/{{ item | regex_replace('\\.j2$', '') }}"
    mode: "0644"
  loop:
    - named.conf.local.j2
    - named.conf.options.j2
    - db_forward.j2
    - db_reverse.j2
  notify: Restart bind9
  become: true
